version: '3.8'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi/local/local_tenstorrent_llm_openapi_v3.json
      - WITH_CREDENTIALS=true  # need for swagger-ui to send session cookie
    volumes:
      - ./docs/openapi:/mnt/openapi
    networks:
      - local_network

  local-inference-api:
    # image: ghcr.io/tenstorrent/project-falcon:v0.0.16
    build:
      context: ./inference-api
      dockerfile: Dockerfile-local
    image: project-falcon/falcon40b-demo:v0.0.17-local
    platform: linux/x86_64
    # ports are only exposed if you want to test an external service
    # use docker-compose internal locak_network for inter-container networking
    ports:
      - "1223:1223"  # reverse proxy with JWT Authrization
      - "7000:7000"  # inference-api
    environment:
      - MOCK_MODEL=1  # mock out model
      - FALCON_40B_2LAYER=1  # running full 60L version, init_kv_cache may OOM
      - MODEL_WEKA_DIR=/mnt/local_weka_mock  # use for server_logs in local testing
      - JWT_SECRET=test-secret-456
      - FLASK_SECRET=flask-secret-8904873
    volumes:
      - ./inference-api/src:/mnt/src
      - ./scripts:/mnt/scripts
      - ./inference-api/run_inference_api.sh:/mnt/run_inference_api.sh
      - ./inference-api/local_weka_mock:/mnt/local_weka_mock
    command: ["bash", "/mnt/run_inference_api.sh"]
    networks:
      - local_network

  conversation-api:
    build:
      context: ./conversation-api
      dockerfile: Dockerfile
    image: project-falcon/conversation-api:v0.0.1
    platform: linux/x86_64
    # ports are only exposed if you want to test an external service
    # use docker-compose internal locak_network for inter-container networking
    ports:
      - "7001:7001"  # make conversation-api available to swagger-ui
    environment:
        # these are test evariables ONLY
        - TT_API_JWT=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX2lkIjoidGVuc3RvcnJlbnQiLCJ0b2tlbl9pZCI6ImRlYnVnLXRlc3QifQ.LZeuFMVFzgxD91sDR79qlfDogPHUCG9lLopctYKYvnI
        - TT_FALCON_40B_INFERENCE_API_URL=http://local-inference-api:7000/inference/falcon40b
        - FLASK_SECRET=flask-secret-8904873
    volumes:
      - ./conversation-api/src:/mnt/src
    # command: ["python", "-u", "/app/src/conversation_api_server.py"]
    command: ["sh", "/app/run_conversation_api.sh"]
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
